version: '3.8'
services:
    nginx:
        image: "nginx:stable-alpine"
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d
        ports:
            - "80:80"
        depends_on:
            - php
        container_name: graphql_nginx
    php:
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www
        ports:
            -   8000:8000
        depends_on:
            -   database
            -   redis
        container_name: php
    database:
        image: postgres:latest
        restart: always
        volumes:
            - ./tmp/db:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: jobpilot
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
        ports:
            - 8101:5432
        container_name: database
    redis:
        image: redis:alpine
        command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
        ports:
            -   6379:6379
        container_name: redis

